"""init

Revision ID: f74a2412c63a
Revises: 
Create Date: 2021-03-12 14:45:50.743698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74a2412c63a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('corequisites', sa.String(), nullable=True),
    sa.Column('exclusions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('flairs',
    sa.Column('flair_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('flair_id')
    )
    op.create_table('programs',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('program_association',
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.code'], ),
    sa.ForeignKeyConstraint(['program'], ['programs.code'], )
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('flair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flair_id'], ['flairs.flair_id'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('review_tags',
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review'], ['reviews.review_id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_tags')
    op.drop_table('reviews')
    op.drop_table('users')
    op.drop_table('program_association')
    op.drop_table('tags')
    op.drop_table('programs')
    op.drop_table('flairs')
    op.drop_table('courses')
    # ### end Alembic commands ###
